name: unifonter
base: core20
license: GPL-3.0-or-later
summary: unifonter is a filter that tries to make ASCII fancy with the help of Unicode
description: |
  `unifonter` is meant to be used as a filter, or as a quick lookup /
  translation tool. So you can use it either like

      $ man man | unifonter
      ğ”ğ”„ğ”‘(1)                   ğ”ğ”ğ”«ğ”²ğ”ğ”© ğ”­ğ”ğ”¤ğ”¢ğ”¯ ğ”²ğ”±ğ”¦ğ”©ğ”°                   ğ”ğ”„ğ”‘(1)

      ğ”‘ğ”„ğ”ğ”ˆ
             ğ”ªğ”ğ”« - ğ”ğ”« ğ”¦ğ”«ğ”±ğ”¢ğ”¯ğ”£ğ”ğ” ğ”¢ ğ”±ğ”¬ ğ”±ğ”¥ğ”¢ ğ”°ğ”¶ğ”°ğ”±ğ”¢ğ”ª ğ”¯ğ”¢ğ”£ğ”¢ğ”¯ğ”¢ğ”«ğ” ğ”¢ ğ”ªğ”ğ”«ğ”²ğ”ğ”©ğ”°

      ğ”–ğ”œğ”‘ğ”’ğ”“ğ”–â„‘ğ”–
             ğ”ªğ”ğ”« [ğ”ªğ”ğ”« ğ”¬ğ”­ğ”±ğ”¦ğ”¬ğ”«ğ”°] [[ğ”°ğ”¢ğ” ğ”±ğ”¦ğ”¬ğ”«] ğ”­ğ”ğ”¤ğ”¢ ...] ...
             ğ”ªğ”ğ”« -ğ”¨ [ğ”ğ”­ğ”¯ğ”¬ğ”­ğ”¬ğ”° ğ”¬ğ”­ğ”±ğ”¦ğ”¬ğ”«ğ”°] ğ”¯ğ”¢ğ”¤ğ”¢ğ”µğ”­ ...
             ğ”ªğ”ğ”« -ğ” [ğ”ªğ”ğ”« ğ”¬ğ”­ğ”±ğ”¦ğ”¬ğ”«ğ”°] [ğ”°ğ”¢ğ” ğ”±ğ”¦ğ”¬ğ”«] ğ”±ğ”¢ğ”¯ğ”ª ...
             ğ”ªğ”ğ”« -ğ”£ [ğ”´ğ”¥ğ”ğ”±ğ”¦ğ”° ğ”¬ğ”­ğ”±ğ”¦ğ”¬ğ”«ğ”°] ğ”­ğ”ğ”¤ğ”¢ ...

  or

      $ unifonter Hello
      â„ğ•–ğ•ğ•ğ• 

  Several different styles are supported; use `-k` followed by a style
  combination you want, otherwise one is chosen at random.

  Supported styles can be seen via `unifonter -d`:

  * ğğ¨ğ¥ğ
  * ğ¼ğ‘¡ğ‘ğ‘™ğ‘–ğ‘
  * ğ‘©ğ’ğ’ğ’… ğ‘°ğ’•ğ’‚ğ’ğ’Šğ’„
  * ğ–²ğ–ºğ—‡ğ—Œ-ğ–²ğ–¾ğ—‹ğ—‚ğ–¿
  * ğ—¦ğ—®ğ—»ğ˜€-ğ—¦ğ—²ğ—¿ğ—¶ğ—³ ğ—•ğ—¼ğ—¹ğ—±
  * ğ˜šğ˜¢ğ˜¯ğ˜´-ğ˜šğ˜¦ğ˜³ğ˜ªğ˜§ ğ˜ğ˜µğ˜¢ğ˜­ğ˜ªğ˜¤
  * ğ™ğ™–ğ™£ğ™¨-ğ™ğ™šğ™§ğ™ğ™› ğ˜½ğ™¤ğ™¡ğ™™ ğ™„ğ™©ğ™–ğ™¡ğ™ğ™˜
  * ğ’®ğ’¸ğ“‡ğ’¾ğ“…ğ“‰
  * ğ“‘ğ“¸ğ“µğ“­ ğ“¢ğ“¬ğ“»ğ“²ğ“¹ğ“½
  * ğ”»ğ• ğ•¦ğ•“ğ•ğ•–-ğ•Šğ•¥ğ•£ğ•¦ğ•”ğ•œ
  * ğ”‰ğ”¯ğ”ğ”¨ğ”±ğ”²ğ”¯
  * ğ•­ğ–”ğ–‘ğ–‰ ğ•±ğ–—ğ–†ğ–ğ–™ğ–šğ–—
  * Sá´á´€ÊŸÊŸ-Cá´€á´˜êœ±
  * ğ™¼ğš˜ğš—ğš˜ğšœğš™ğšŠğšŒğš
  * ï¼¦ï½•ï½Œï½Œï½—ï½‰ï½„ï½”ï½ˆ

  but note the order of the letters doesn't matter (`-k bis` is the same
  as `-k sib`), so if you find that you think "fraktur bold" instead of
  "bold fraktur", just go with it.

  Some other options are supported; see the output of `-h`.

adopt-info: unifonter

apps:
  unifonter:
    environment:
      LC_ALL: C.UTF-8
    plugs:
      - home
      - removable-media
    command: ./unifonter.py
    adapter: none

grade: stable
confinement: strict

architectures:
  - build-on: amd64
    run-on: all
parts:
  unifonter:
    plugin: dump
    source: .
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$( ./unifonter.py -v )"
    stage:
      - unifonter.py
